services:

  postgres:
    container_name: nextjs-auth-postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

#  mongodb:
#    container_name: nextjs-auth-mongo
#    image: mongo
#    command: [ "mongod", "--auth" ]
#    volumes:
#      - mongo_data:/data/db
#    restart: always
#    ports:
#      - "27017:27017"
#    env_file:
#      - .env

volumes:
  postgres_data:
# mongo_data: